---
- name: editing motd file
  hosts: all
  become: yes
  roles:
      - role: post-install
      - role: geerlingguy.java
        when: "ansible_os_family == 'Debian'"
        java_packages:
           - openjdk-8-jdk